version: "3"

services:
  node:
    build: .
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
